### PRUEBAS RÁPIDAS (VS Code con extensión REST Client)
GET http://localhost:3001/health

### Crear usuario
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

### Crear nota
POST http://localhost:3001/notes
Content-Type: application/json

{
  "uid": "<UID_DEL_USUARIO>",
  "text": "Hola Firestore"
}